version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: ContDBpractMod3
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./save_data.sql:/docker-entrypoint-initdb.d/02_save_data.sql
    restart: always

volumes:
  postgres_data:
    driver: local